# Shared definition block
shared:
  # Source: https://hub.docker.com/r/library/buildpack-deps/
  image: node:10
# Job definition block
jobs:
  main:
    requires: [~pr, ~commit]
    # Steps definition block.
    steps:
      - export: export GREETING="Hello, world!"
      - hello: echo $GREETING
      - set-metadata: meta set example.coverage 99.95
  test:
    requires: [main] # second_job will run after main job is done
    steps:
      - prepare-npm: npm set progress=false && npm config set depth 0 && npm cache clean --force
      - install: npm i && mkdir /ng-app && cp -R ./node_modules ./ng-app
      - cd: cd /ng-app
      - build: $(npm bin)/ng build --prod
      - get-metadata: meta get example
